### ISSUE TITLE
The method that you used to calculate NMI is not correct

### ISSUE THREAD

**Issue by lirenjie95** [aparna1996/clustering_validation#1]
I'm afraid you made a mistake in cluster_validation.py, line 61.

NMI = I/sqrt(H(C)*H(P))

not 2*I/(H(C)+H(P))

you could view my solution [here](https://github.com/lirenjie95/DataMining/blob/master/DataMining-UIUC/PatternDiscovery/Validation.cpp)(C++)

**Comment by aparna1996** [comment]
Thank you for pointing out the mistake. I have corrected it.
